---
image:
  name: $CI_REGISTRY/le-garff-yoann/docker-reveal-md:latest
  entrypoint: [ "/bin/sh", "-c" ]

stages:
  - build
  - release
  
cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - public

build:
  stage: build
  script: reveal-md index.md --static public

pages:
  stage: release
  script: test -f public/index.html
  artifacts:
    paths:
      - public
  only:
    - master
    - tags
